webtalk_init -webtalk_dir Z:/6B/processor/Processor_Design_Project/Processor_Vivado/Contributors/Shamal/GenPurReg/GenPurReg.sim/sim_1/behav/xsim/xsim.dir/ProcessorTB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jun 24 16:02:51 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c121f558-6a24-452d-b6cc-a3957c4017d3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3187334876f94aed840dfe80b96e32f5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "445" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2712 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "17" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "173 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "38 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "329" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "74" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.75_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "80256_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1843781977 -regid "" -xml Z:/6B/processor/Processor_Design_Project/Processor_Vivado/Contributors/Shamal/GenPurReg/GenPurReg.sim/sim_1/behav/xsim/xsim.dir/ProcessorTB_behav/webtalk/usage_statistics_ext_xsim.xml -html Z:/6B/processor/Processor_Design_Project/Processor_Vivado/Contributors/Shamal/GenPurReg/GenPurReg.sim/sim_1/behav/xsim/xsim.dir/ProcessorTB_behav/webtalk/usage_statistics_ext_xsim.html -wdm Z:/6B/processor/Processor_Design_Project/Processor_Vivado/Contributors/Shamal/GenPurReg/GenPurReg.sim/sim_1/behav/xsim/xsim.dir/ProcessorTB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
