module DECODER(
    input clk,
    input [5:0] from_cu,
    input [5:0] from_selector,
    output reg [0:0] out_AR,
    output reg [0:0] out_PC,
    output reg [0:0] out_MIDR,
    output reg [0:0] out_MDDR_BUS,
    output reg [0:0] out_MDDR_IM,
    output reg [0:0] out_MDDR_DM,
    output reg [0:0] out_BASE,
    output reg [0:0] out_I,
    output reg [0:0] out_I_Ref,
    output reg [0:0] out_Base_A,
    output reg [0:0] out_J,
    output reg [0:0] out_J_Ref,
    output reg [0:0] out_Base_B,
    output reg [0:0] out_K,
    output reg [0:0] out_K_Ref,
    output reg [0:0] out_P,
    output reg [0:0] out_R
    );
    reg [5:0] reg_select;
always @(*)
    begin
    if (from_selector==5'd0)reg_select=from_cu;
    else reg_select=from_selector;
    case (reg_select)
        5'd0:begin
            out_AR=0;      
            out_PC=0;     
            out_MIDR=0;    
            out_MDDR_BUS=0;
            out_MDDR_IM=0; 
            out_MDDR_DM=0; 
            out_BASE=0;    
            out_I=0;       
            out_I_Ref=0;   
            out_Base_A=0;  
            out_J=0;       
            out_J_Ref=0;   
            out_Base_B=0;  
            out_K=0;       
            out_K_Ref=0;   
            out_P=0;       
            out_R=0;                    
        end
        5'd1:begin
            out_AR=1;      
            out_PC=0;     
            out_MIDR=0;    
            out_MDDR_BUS=0;
            out_MDDR_IM=0; 
            out_MDDR_DM=0; 
            out_BASE=0;    
            out_I=0;       
            out_I_Ref=0;   
            out_Base_A=0;  
            out_J=0;       
            out_J_Ref=0;   
            out_Base_B=0;  
            out_K=0;       
            out_K_Ref=0;   
            out_P=0;       
            out_R=0;                      
        end
        5'd2:begin
            out_AR=0;      
            out_PC=1;     
            out_MIDR=0;    
            out_MDDR_BUS=0;
            out_MDDR_IM=0; 
            out_MDDR_DM=0; 
            out_BASE=0;    
            out_I=0;       
            out_I_Ref=0;   
            out_Base_A=0;  
            out_J=0;       
            out_J_Ref=0;   
            out_Base_B=0;  
            out_K=0;       
            out_K_Ref=0;   
            out_P=0;       
            out_R=0;                      
        end
        5'd3:begin
            out_AR=0;      
            out_PC=0;     
            out_MIDR=1;    
            out_MDDR_BUS=0;
            out_MDDR_IM=0; 
            out_MDDR_DM=0; 
            out_BASE=0;    
            out_I=0;       
            out_I_Ref=0;   
            out_Base_A=0;  
            out_J=0;       
            out_J_Ref=0;   
            out_Base_B=0;  
            out_K=0;       
            out_K_Ref=0;   
            out_P=0;       
            out_R=0;                      
        end
        5'd4:begin
            out_AR=0;      
            out_PC=0;     
            out_MIDR=0;    
            out_MDDR_BUS=1;
            out_MDDR_IM=0; 
            out_MDDR_DM=0; 
            out_BASE=0;    
            out_I=0;       
            out_I_Ref=0;   
            out_Base_A=0;  
            out_J=0;       
            out_J_Ref=0;   
            out_Base_B=0;  
            out_K=0;       
            out_K_Ref=0;   
            out_P=0;       
            out_R=0;                    
        end
        5'd5:begin
            out_AR=0;      
            out_PC=0;     
            out_MIDR=0;    
            out_MDDR_BUS=0;
            out_MDDR_IM=0; 
            out_MDDR_DM=1; 
            out_BASE=0;    
            out_I=0;       
            out_I_Ref=0;   
            out_Base_A=0;  
            out_J=0;       
            out_J_Ref=0;   
            out_Base_B=0;  
            out_K=0;       
            out_K_Ref=0;   
            out_P=0;       
            out_R=0;                    
        end
        5'd6:begin
            out_AR=0;      
            out_PC=0;     
            out_MIDR=0;    
            out_MDDR_BUS=0;
            out_MDDR_IM=1; 
            out_MDDR_DM=0; 
            out_BASE=0;    
            out_I=0;       
            out_I_Ref=0;   
            out_Base_A=0;  
            out_J=0;       
            out_J_Ref=0;   
            out_Base_B=0;  
            out_K=0;       
            out_K_Ref=0;   
            out_P=0;       
            out_R=0;                    
        end
        5'd7:begin
            out_AR=0;      
            out_PC=0;     
            out_MIDR=0;    
            out_MDDR_BUS=0;
            out_MDDR_IM=0; 
            out_MDDR_DM=0; 
            out_BASE=1;    
            out_I=0;       
            out_I_Ref=0;   
            out_Base_A=0;  
            out_J=0;       
            out_J_Ref=0;   
            out_Base_B=0;  
            out_K=0;       
            out_K_Ref=0;   
            out_P=0;       
            out_R=0;                    
        end
        5'd8:begin
            out_AR=0;      
            out_PC=0;     
            out_MIDR=0;    
            out_MDDR_BUS=0;
            out_MDDR_IM=0; 
            out_MDDR_DM=0; 
            out_BASE=0;    
            out_I=1;       
            out_I_Ref=0;   
            out_Base_A=0;  
            out_J=0;       
            out_J_Ref=0;   
            out_Base_B=0;  
            out_K=0;       
            out_K_Ref=0;   
            out_P=0;       
            out_R=0;                    
        end
        5'd9:begin
            out_AR=0;      
            out_PC=0;     
            out_MIDR=0;    
            out_MDDR_BUS=0;
            out_MDDR_IM=0; 
            out_MDDR_DM=0; 
            out_BASE=0;    
            out_I=0;       
            out_I_Ref=1;   
            out_Base_A=0;  
            out_J=0;       
            out_J_Ref=0;   
            out_Base_B=0;  
            out_K=0;       
            out_K_Ref=0;   
            out_P=0;       
            out_R=0;                    
        end
        5'd10:begin
            out_AR=0;      
            out_PC=0;     
            out_MIDR=0;    
            out_MDDR_BUS=0;
            out_MDDR_IM=0; 
            out_MDDR_DM=0; 
            out_BASE=0;    
            out_I=0;       
            out_I_Ref=0;   
            out_Base_A=1;  
            out_J=0;       
            out_J_Ref=0;   
            out_Base_B=0;  
            out_K=0;       
            out_K_Ref=0;   
            out_P=0;       
            out_R=0;                    
        end
        5'd11:begin
            out_AR=0;      
            out_PC=0;     
            out_MIDR=0;    
            out_MDDR_BUS=0;
            out_MDDR_IM=0; 
            out_MDDR_DM=0; 
            out_BASE=0;    
            out_I=0;       
            out_I_Ref=0;   
            out_Base_A=0;  
            out_J=1;       
            out_J_Ref=0;   
            out_Base_B=0;  
            out_K=0;       
            out_K_Ref=0;   
            out_P=0;       
            out_R=0;                    
        end
        5'd12:begin
            out_AR=0;      
            out_PC=0;     
            out_MIDR=0;    
            out_MDDR_BUS=0;
            out_MDDR_IM=0; 
            out_MDDR_DM=0; 
            out_BASE=0;    
            out_I=0;       
            out_I_Ref=0;   
            out_Base_A=0;  
            out_J=0;       
            out_J_Ref=1;   
            out_Base_B=0;  
            out_K=0;       
            out_K_Ref=0;   
            out_P=0;       
            out_R=0;                    
        end
        5'd13:begin
            out_AR=0;      
            out_PC=0;     
            out_MIDR=0;    
            out_MDDR_BUS=0;
            out_MDDR_IM=0; 
            out_MDDR_DM=0; 
            out_BASE=0;    
            out_I=0;       
            out_I_Ref=0;   
            out_Base_A=0;  
            out_J=0;       
            out_J_Ref=0;   
            out_Base_B=1;  
            out_K=0;       
            out_K_Ref=0;   
            out_P=0;       
            out_R=0;                    
        end
        5'd14:begin
            out_AR=0;      
            out_PC=0;     
            out_MIDR=0;    
            out_MDDR_BUS=0;
            out_MDDR_IM=0; 
            out_MDDR_DM=0; 
            out_BASE=0;    
            out_I=0;       
            out_I_Ref=0;   
            out_Base_A=0;  
            out_J=0;       
            out_J_Ref=0;   
            out_Base_B=0;  
            out_K=1;       
            out_K_Ref=0;   
            out_P=0;       
            out_R=0;                    
        end
        5'd15:begin
            out_AR=0;      
            out_PC=0;     
            out_MIDR=0;    
            out_MDDR_BUS=0;
            out_MDDR_IM=0; 
            out_MDDR_DM=0; 
            out_BASE=0;    
            out_I=0;       
            out_I_Ref=0;   
            out_Base_A=0;  
            out_J=0;       
            out_J_Ref=0;   
            out_Base_B=0;  
            out_K=0;       
            out_K_Ref=1;   
            out_P=0;       
            out_R=0;                    
        end
        5'd16:begin
            out_AR=0;      
            out_PC=0;     
            out_MIDR=0;    
            out_MDDR_BUS=0;
            out_MDDR_IM=0; 
            out_MDDR_DM=0; 
            out_BASE=0;    
            out_I=0;       
            out_I_Ref=0;   
            out_Base_A=0;  
            out_J=0;       
            out_J_Ref=0;   
            out_Base_B=0;  
            out_K=0;       
            out_K_Ref=0;   
            out_P=1;       
            out_R=0;                    
        end
        5'd17:begin
            out_AR=0;      
            out_PC=0;     
            out_MIDR=0;    
            out_MDDR_BUS=0;
            out_MDDR_IM=0; 
            out_MDDR_DM=0; 
            out_BASE=0;    
            out_I=0;       
            out_I_Ref=0;   
            out_Base_A=0;  
            out_J=0;       
            out_J_Ref=0;   
            out_Base_B=0;  
            out_K=0;       
            out_K_Ref=0;   
            out_P=0;       
            out_R=1;                    
        end
        5'd18:begin
            out_AR=1;      
            out_PC=0;     
            out_MIDR=0;    
            out_MDDR_BUS=0;
            out_MDDR_IM=1; 
            out_MDDR_DM=0; 
            out_BASE=0;    
            out_I=0;       
            out_I_Ref=0;   
            out_Base_A=0;  
            out_J=0;       
            out_J_Ref=0;   
            out_Base_B=0;  
            out_K=0;       
            out_K_Ref=0;   
            out_P=0;       
            out_R=0;                    
        end
        5'd19:begin
            out_AR=1;      
            out_PC=0;     
            out_MIDR=0;    
            out_MDDR_BUS=0;
            out_MDDR_IM=0; 
            out_MDDR_DM=1; 
            out_BASE=0;    
            out_I=0;       
            out_I_Ref=0;   
            out_Base_A=0;  
            out_J=0;       
            out_J_Ref=0;   
            out_Base_B=0;  
            out_K=0;       
            out_K_Ref=0;   
            out_P=0;       
            out_R=0;                    
        end
        default: 
        begin
            out_AR=0;      
            out_PC=0;     
            out_MIDR=0;    
            out_MDDR_BUS=0;
            out_MDDR_IM=0; 
            out_MDDR_DM=0; 
            out_BASE=0;    
            out_I=0;       
            out_I_Ref=0;   
            out_Base_A=0;  
            out_J=0;       
            out_J_Ref=0;   
            out_Base_B=0;  
            out_K=0;       
            out_K_Ref=0;   
            out_P=0;       
            out_R=0;                    
        end
        endcase
    end
endmodule  